name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. INSTALAR JAVA (Necesario para compilar Android)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 2. INSTALAR PYTHON
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. INSTALAR FLET (Tu versión estable)
      - name: Install Flet CLI
        run: |
          pip install flet==0.23.2
          pip install opencv-python-headless

      # 4. INSTALAR FLUTTER (Versión compatible con Flet 0.23.2)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Bajamos un poco la versión para asegurar compatibilidad

      # 5. ACEPTAR LICENCIAS DE ANDROID (Vital para evitar errores)
      - name: Accept Android Licenses
        run: |
          flutter doctor --android-licenses --yes
          flutter doctor -v

      # 6. CONSTRUIR EL APK
      - name: Build APK
        run: |
          flet build apk --permissions WRITE_EXTERNAL_STORAGE READ_EXTERNAL_STORAGE --include-packages opencv-python-headless
          
      # 7. SUBIR EL ARCHIVO
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/apk/*.apk
