name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Actualizado a v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Actualizado a v5
        with:
          python-version: '3.10'

      - name: Install Flet CLI
        run: pip install flet==0.23.2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'

      - name: Build APK
        # Agregamos --include-packages para asegurar que OpenCV vaya dentro
        run: |
          flet build apk --permissions WRITE_EXTERNAL_STORAGE READ_EXTERNAL_STORAGE --include-packages opencv-python-headless
          
      - name: Upload APK
        uses: actions/upload-artifact@v4  # <--- AQUÃ ESTABA EL ERROR (v3 -> v4)
        with:
          name: app-release
          path: build/apk/*.apk
